# Generated by Django 4.1.1 on 2022-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_big', models.CharField(max_length=300)),
                ('cat_small', models.CharField(max_length=300)),
                ('same_line', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_big', models.CharField(max_length=300)),
                ('dog_small', models.CharField(max_length=300)),
                ('same_line', models.CharField(max_length=300)),
            ],
        ),
    ]
