# Generated by Django 4.1.1 on 2022-09-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_cat_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.cat')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.dog')),
            ],
        ),
    ]
