# Generated by Django 4.1.1 on 2022-09-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_signals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signals',
            new_name='TestSignals',
        ),
    ]
