# Generated by Django 4.1.1 on 2022-09-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_rename_signals_testsignals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsignals',
            old_name='date',
            new_name='date_changed',
        ),
        migrations.AddField(
            model_name='testsignals',
            name='previous_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
