# Generated by Django 4.1.1 on 2022-09-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_rename_date_testsignals_date_changed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsignals',
            old_name='date_changed',
            new_name='date',
        ),
    ]
